/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info5100.assignment4;


import UI.Abnormal.AbnormalJPanel;
import UI.admin.AdminJPanel;
import info5100.assignment4.model.Admin;
import info5100.assignment4.model.Encounter;
import info5100.assignment4.model.Patient;
import info5100.assignment4.model.Person;
import info5100.assignment4.model.Residence;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author An
 */
public class INFO5100Assignment4 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Admin admin ;
    
    public INFO5100Assignment4() {
        initComponents();
        admin = new Admin();
        Residence residence = new Residence("50","Station Landing","Medford");
        Person person1 = new Person("Mike",20,residence,100.5d);
        Person person2 = new Person("Marry",21,new Residence("150", "hunting avenue", "Boston"),145.0d,true,new ArrayList<Encounter>());
        Person person3 = new Person("Vivi",25,new Residence("100", "hunting avenue", "Boston"),80.0d,true,new ArrayList<Encounter>());
         Person person4 = new Person("Oliver",23,new Residence("100", "Station Landing", "Boston"),80.0d,true,new ArrayList<Encounter>());
        ArrayList<Person> personDirectory = new ArrayList<>();
        personDirectory.add(person1);
        personDirectory.add(person2);
        personDirectory.add(person3);
         personDirectory.add(person4);
        admin.setPersonDirectory(personDirectory);
        ArrayList<Person> patientDirectory = new ArrayList<>();
        patientDirectory.add(person2);
        patientDirectory.add(person3);
        admin.setPatientDirectory(patientDirectory);
        setSize(830,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DashBoardPanel = new javax.swing.JPanel();
        adminButton = new javax.swing.JButton();
        abnormalCaseButtorn = new javax.swing.JButton();
        UserJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminButton.setText("admin ");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        abnormalCaseButtorn.setText("abnormal cases");
        abnormalCaseButtorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abnormalCaseButtornActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashBoardPanelLayout = new javax.swing.GroupLayout(DashBoardPanel);
        DashBoardPanel.setLayout(DashBoardPanelLayout);
        DashBoardPanelLayout.setHorizontalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abnormalCaseButtorn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashBoardPanelLayout.setVerticalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(adminButton)
                .addGap(105, 105, 105)
                .addComponent(abnormalCaseButtorn)
                .addGap(141, 141, 141))
        );

        jSplitPane1.setLeftComponent(DashBoardPanel);

        UserJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(UserJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abnormalCaseButtornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abnormalCaseButtornActionPerformed
        // TODO add your handling code here:
        AbnormalJPanel abnormalJPanel = new AbnormalJPanel(UserJPanel,admin);
        UserJPanel.add("AdminJPanel",abnormalJPanel);
        CardLayout layout = (CardLayout)UserJPanel.getLayout();
        layout.next(UserJPanel);
    }//GEN-LAST:event_abnormalCaseButtornActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        AdminJPanel adminJFrame = new AdminJPanel(UserJPanel,admin);
        UserJPanel.add("AdminJPanel",adminJFrame);
        CardLayout layout = (CardLayout)UserJPanel.getLayout();
        layout.next(UserJPanel);
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INFO5100Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INFO5100Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INFO5100Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INFO5100Assignment4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INFO5100Assignment4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashBoardPanel;
    private javax.swing.JPanel UserJPanel;
    private javax.swing.JButton abnormalCaseButtorn;
    private javax.swing.JButton adminButton;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
